import math

print(math.pi)
print(math.tau)#2times pie
print(math.e)
print(math.inf)#infinity
print(math.nan)#not a number

#number theoritic and represntation of function---------------->

r = math.ceil(2.5)
print(r)
#-------------------------------------------

r = math.fabs(-32.4)#it will give postive valur
print(r)

#------------------------------------------------>

r = math.factorial(5)
print(r)

#--------------------------------------->
r = math.floor(-32.4) #it will interger next num
print(r)

#---------------------------------------------->

r = math.fsum([2,4,33.4,0])
print(r)
#----------------------------------------------->

r = math.remainder(10,4) #10/4
print(r)
#------------------------------------------->

#power and logarithmic function

r = math.log(10)
print(r)
#------------------------------------------>
r = math.sqrt(4)
print(r)

#--------------------------------------------
r = math.pow(2,3)
print(r)

#--------------------------------------------

r = math.exp(10)
print(r)

#=============Angular conversion============================

r = math.radians(180)
print(r)

#---------------------------------------

r = math.degrees(math.pi)
print(r)

#==========Trignometric Function========================

#r = math.sin(math.radians(270)) or

i = math.radians(270)
r = math.sin(i)
print(r)

#---------------------------------------------->

i = math.radians(0)
r = math.cos(i)
print(r)

#------------------------------------------------->

i = math.radians(0)
r = math.tan(i)
print(r)
















